---
deployment:
  tasks:
    - export DEPLOYPATH=/home/diogogeadavcloud/validation/
    - /bin/cp -r * $DEPLOYPATH
    - /bin/cp -r /public/* /home/diogogeadavcloud/validation
    - cd $DEPLOYPATH
    - /bin/rm -r /public
    - /bin/rm -r /.git