---
deployment:
  tasks:
    - export DEPLOYPATH=/home/diogogeadavcloud/validation
    - /bin/cp -r * $DEPLOYPATH
    - /bin/cp -r ./.htaccess $DEPLOYPATH
    - /bin/cp -r ./.env $DEPLOYPATH
    - /bin/cp -r ./public/* /home/diogogeadavcloud/public_html/validation
    - /bin/cp -r ./public/.htaccess /home/diogogeadavcloud/public_html/validation
    - /bin/rm -r $DEPLOYPATH/public
    - /bin/rm -r $DEPLOYPATH/.git
    - /bin/rm $DEPLOYPATH/README.md
    - /bin/rm $DEPLOYPATH/.gitignore
    - /bin/rm $DEPLOYPATH/.gitattributes
    - /bin/rm $DEPLOYPATH/.cpanel.yml